### ISSUE TITLE
docker container crash

### ISSUE THREAD

**Issue by hamsterksu** [monitoringartist/zabbix-agent-xxl#2]
Hi 

I try to use your docker image to monitor my docker containers. 

**My system** - ubuntu 14.04
**Docker version** - 1.10.2

**Run command:**

```
docker run --name=zabbix-agent-xxl -h my-hostname -p 31050:10050 -v /:/rootfs -e "ZA_Server=zabbix.marathon.mesos" -e "ZA_ServerActive=zabbix.marathon.mesos" -e "ZA_StartAgents=10" -e "ZA_Timeout=30" --rm monitoringartist/zabbix-agent-xxl-limited:latest
```

**Start error:**

```
Zocker XXL v0.9.1b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to oficial monitoringartist Docker images only.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4e77d7]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Env).Map(0x0, 0x1b)
        /usr/lib/golang/src/github.com/fsouza/go-dockerclient/env.go:159 +0x27
github.com/fsouza/go-dockerclient.(*Env).Get(0x0, 0x7e07e0, 0x4, 0x0, 0x0)
        /usr/lib/golang/src/github.com/fsouza/go-dockerclient/env.go:20 +0x2f
main.main()
        /root/zabbix-agent-docker-commercial/zocker-xxl.go:50 +0xc27

goroutine 10 [select]:
net/http.(*persistConn).readLoop(0xc8200a60b0)
        /usr/lib/golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc8200a60b0)
        /usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:686 +0xc9d
```

**Comment by jangaraj** [comment]
Could you provide command output please?

```
docker info
```

**Comment by hamsterksu** [comment]
docker version

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

```

**Comment by hamsterksu** [comment]
docker info 

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798 GiB
Name: juju-local-machine-12
ID: HM7O:VRJX:BB2X:I6BE:MZ3U:MJUZ:AC5O:VI4Y:FFPF:PAAB:DI24:DRHE
WARNING: No swap limit support
```

**Comment by jangaraj** [comment]
Your problem is Ubuntu. It's in the readme:
Ubuntu users need also `-v /var/run:/var/run`.

**Comment by hamsterksu** [comment]
oh, could you add 2 sections to README with different titles like

### CoreOS, RHEL, CentOS, Boot2docker, Photon OS

```
docker run \
  --name=zabbix-agent-xxl \
  -h `hostname` \
  -p 10050:10050 \
  -v /:/rootfs \
  -e "ZA_Server=<ZABBIX SERVER IP/DNS NAME>" \
  -d monitoringartist/zabbix-agent-xxl-limited:latest
```

### Ubuntu, Debian

Note: add `-v /var/run:/var/run`

```
docker run \
  --name=zabbix-agent-xxl \
  -h `hostname` \
  -p 10050:10050 \
  -v /:/rootfs \
  -v /var/run:/var/run
  -e "ZA_Server=<ZABBIX SERVER IP/DNS NAME>" \
  -d monitoringartist/zabbix-agent-xxl-limited:latest
```

**Comment by jangaraj** [comment]
Sure, but my time is limited. It must be tested and verified. Actually I think that Debian doesn't need `-v /var/run:/var/run`. Feel free to test it and please create PR.
